<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-17T12:31:51 IST" name="Suite" finished-at="2023-08-17T12:32:57 IST" duration-ms="66104">
    <groups>
    </groups>
    <test started-at="2023-08-17T12:31:51 IST" name="Test" finished-at="2023-08-17T12:32:57 IST" duration-ms="66104">
      <class name="com.w3schools.utils.Reports">
        <test-method is-config="true" signature="startReport()[pri:0, instance:com.w3schools.utils.Reports@cb0755b]" started-at="2023-08-17T12:31:51 IST" name="startReport" finished-at="2023-08-17T12:31:51 IST" duration-ms="480" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method is-config="true" signature="endReport()[pri:0, instance:com.w3schools.utils.Reports@cb0755b]" started-at="2023-08-17T12:32:57 IST" name="endReport" finished-at="2023-08-17T12:32:58 IST" duration-ms="572" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- com.w3schools.utils.Reports -->
      <class name="com.w3schools.tests.LoginTest">
        <test-method signature="loginWithInvalidEmail()[pri:0, instance:com.w3schools.tests.LoginTest@28261e8e]" started-at="2023-08-17T12:31:51 IST" name="loginWithInvalidEmail" finished-at="2023-08-17T12:32:45 IST" duration-ms="53296" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.w3schools.tests.LoginTest.loginWithInvalidEmail(LoginTest.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidEmail -->
        <test-method is-config="true" signature="closeAllBrowsers()[pri:0, instance:com.w3schools.tests.LoginTest@28261e8e]" started-at="2023-08-17T12:32:45 IST" name="closeAllBrowsers" finished-at="2023-08-17T12:32:45 IST" duration-ms="321" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAllBrowsers -->
        <test-method signature="loginWithValidCredentials()[pri:0, instance:com.w3schools.tests.LoginTest@28261e8e]" started-at="2023-08-17T12:32:45 IST" name="loginWithValidCredentials" finished-at="2023-08-17T12:32:57 IST" duration-ms="12179" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithValidCredentials -->
        <test-method is-config="true" signature="closeAllBrowsers()[pri:0, instance:com.w3schools.tests.LoginTest@28261e8e]" started-at="2023-08-17T12:32:57 IST" name="closeAllBrowsers" finished-at="2023-08-17T12:32:57 IST" duration-ms="240" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAllBrowsers -->
      </class> <!-- com.w3schools.tests.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
